#!/usr/bin/env python3
"""
SConstruct for openpilot-ui standalone build.

This is a simplified build configuration that:
1. Builds cereal messaging C++ library
2. Builds msgq/visionipc C++ library
3. Generates font files for UI
"""

import os
import subprocess
from pathlib import Path

# Get the project root
BASEDIR = Path(os.path.dirname(os.path.abspath(__file__)))

# Detect architecture
ARCH = os.environ.get("ARCH", "x86_64" if os.uname().machine == "x86_64" else "Darwin")

# Configure environment
env = Environment(
    CC=os.environ.get("CC", "clang" if ARCH != "Darwin" else "gcc"),
    CXX=os.environ.get("CXX", "clang++" if ARCH != "Darwin" else "g++"),
    CFLAGS=["-Wall", "-Wextra"],
    CXXFLAGS=["-std=c++17", "-Wall", "-Wextra"],
    CPPPATH=[str(BASEDIR / "cereal" / "include"), str(BASEDIR / "msgq")],
    LIBPATH=[str(BASEDIR / "cereal"), str(BASEDIR / "msgq")],
)

# Add capnp include path (use system capnp or from cereal)
try:
    result = subprocess.run(["capnp", "--version"], capture_output=True, text=True)
    capnp_version = result.stdout.strip()
    print(f"Found capnp: {capnp_version}")

    # Get capnp include path
    result = subprocess.run(["pkg-config", "--cflags", "capnp"], capture_output=True, text=True)
    if result.returncode == 0:
        capnp_cflags = result.stdout.strip()
        # Parse include paths
        for flag in capnp_cflags.split():
            if flag.startswith("-I"):
                env.Append(CPPPATH=[flag[2:]])
except Exception as e:
    print(f"Warning: capnp not found: {e}")

# Build targets
if GetOption("help"):
    print("""
Openpilot-UI Build System

Usage:
    scons              # Build everything
    scons --clean      # Clean build artifacts
    scons fonts        # Build font files only
    scons libs         # Build C++ libraries only

Requirements:
    - Python 3.11+
    - capnproto (capnp)
    - clang/gcc compiler
    """)
else:
    # Build font files
    font_src_dir = BASEDIR / "selfdrive" / "assets" / "fonts"
    if font_src_dir.exists():
        font_files = list(font_src_dir.glob("*.ttf")) + list(font_src_dir.glob("*.otf"))
        print(f"Found {len(font_files)} font files")

        # Copy pre-built .fnt and .png files if they exist
        # Otherwise, they should be generated by the original project's build

    # The prebuilt libraries should already be in place
    # cereal/libcereal.a, cereal/libsocketmaster.a
    # msgq/libmsgq.a, msgq/libvisionipc.a

    print(f"Build configuration:")
    print(f"  Architecture: {ARCH}")
    print(f"  Base directory: {BASEDIR}")
    print(f"  Compiler: {env['CC']}")

    # Check for prebuilt libraries
    libs_ok = True
    for lib in ["cereal/libcereal.a", "cereal/libsocketmaster.a", "msgq/libmsgq.a", "msgq/libvisionipc.a"]:
        lib_path = BASEDIR / lib
        if lib_path.exists():
            print(f"  Found: {lib}")
        else:
            print(f"  Missing: {lib}")
            libs_ok = False

    if not libs_ok:
        print("\nWarning: Some libraries are missing.")
        print("Please copy them from a built openpilot repository or build them manually.")